#Comments:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: tramirez
  labels:
    app: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  minReadySeconds: 20
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: db-secret
        name: app-deployment
        image:  registry.dev.afsmtddso.com/tramirez-harbor-project/app:971c881-08fcbd5
        ports:
        - containerPort: 5000
